[package]
name = "raylib_project"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
raylib = { version = "5.0" }


[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1